version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DB_NAME=Haleji
      - DB_SERVER=db
      - DB_USERNAME=sa
      - DB_PASSWORD=Admin.Password12
      - DEPLOY=Cloud
    ports:
      - "80"
      - "443"