version: '3.4'

networks:
  uit-inventory:

services:
  web:
    image: haleji-web
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - DB_NAME=Haleji
    - DB_SERVER=db
    - DB_USERNAME=sa
    - DB_PASSWORD=Admin.1234
    - TRUSTED=False
    build:
      context: ./Haleji.Base
      dockerfile: Dockerfile
    ports:
    - "80"
    - "443"
    networks:
    - uit-inventory
    depends_on:
    - db
  
  db:
    image: haleji-database
    build:
      context: .
      dockerfile: Haleji.Base/database/Dockerfile.database
    networks:
    - uit-inventory
    volumes:
    - mssqldata:/var/opt/mssql

volumes:
  mssqldata:

