from mcr.microsoft.com/mssql/server:2019-latest
ENV SA_PASSWORD Admin.
ENV ACCEPT_EULA Y
ENV MSSQL_SA_PASSWORD King.1234

copy ./Haleji.Base/database/ /

USER root
RUN chmod +x entrypoint.sh
RUN chmod +x run-script.sh

ENTRYPOINT ["/bin/bash","entrypoint.sh"]
CMD ["/opt/mssql/bin/sqlservr"]

